export enum IntakeState {
    DRAFT = 'DRAFT',
    SUBMITTED = 'SUBMITTED',
    TRIAGE_PENDING = 'TRIAGE_PENDING',
    TRIAGED = 'TRIAGED',
    ASSIGNED_TO_DOCTOR = 'ASSIGNED_TO_DOCTOR',
    CONSULTED = 'CONSULTED',
    TREATMENT_STARTED = 'TREATMENT_STARTED',
    COMPLETED = 'COMPLETED',
    FOLLOW_UP_REQUIRED = 'FOLLOW_UP_REQUIRED',
}

export enum IntakePriority {
    LOW = 'LOW',
    MEDIUM = 'MEDIUM',
    HIGH = 'HIGH',
}
